"""Added measurement table

Revision ID: 8ac42d3270f5
Revises: 2309ad69b03a
Create Date: 2023-06-15 20:24:47.632489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac42d3270f5'
down_revision = '2309ad69b03a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('timestamp', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('insideHumidity', sa.Float(), nullable=False),
    sa.Column('outsideHumidity', sa.Float(), nullable=False),
    sa.Column('insideTemperature', sa.Float(), nullable=False),
    sa.Column('outsideTemperature', sa.Float(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('pumpRelayState', sa.Boolean(), nullable=False),
    sa.Column('humidifierRelayState', sa.Boolean(), nullable=False),
    sa.Column('reboot', sa.Boolean(), nullable=False),
    sa.Column('pidKp', sa.Float(), nullable=False),
    sa.Column('pidKi', sa.Float(), nullable=False),
    sa.Column('pidKd', sa.Float(), nullable=False),
    sa.Column('humidityUpperBoundary', sa.Integer(), nullable=False),
    sa.Column('humidityLowerBoundary', sa.Integer(), nullable=False),
    sa.Column('pumpTemperatureDelta', sa.Float(), nullable=False),
    sa.Column('targetTemperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
